# Generated by Django 5.1.1 on 2024-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='#', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hello i am a user of infoCric', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_name',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
