# Generated by Django 5.1.1 on 2024-10-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_profile_avatar_profile_bio_alter_profile_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_name',
        ),
    ]
